import { type NextPage } from "next";
import Head from "next/head";

import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import Spinner from "~/components/Spinner";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "" });
  const { data: sessionData } = useSession();
  return (
    <>
      <Head>
        <title>גת אביגדור UI</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        {
          <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
            <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
              <span className="text-[hsl(280,100%,70%)]">Biz</span> Mode
            </h1>

            <div className="flex flex-col items-center gap-2">
              {/* <p className="text-2xl text-white">
                {hello.data ? hello.data.greeting : "טוען"}
              </p> */}
              <AuthShowcase />
            </div>
          </div>
        }
      </main>
    </>
  );
};

export default Home;

export const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();
  const { push } = useRouter();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );
  useEffect(() => {
    // signOut();
    if (sessionData) push("/mainDashboard");
  }, [sessionData]);

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {secretMessage && sessionData && (
          <div>
            <p>
              {" "}
              <span> מתחבר </span>
              <span>{sessionData.user?.name}</span>
            </p>
            <Spinner />
          </div>
        )}
      </p>
      {!sessionData && (
        <button
          className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
          onClick={() => {
            signIn()
              .then((res) => console.log({ res }))
              .finally(() => {});
          }}
        >
          {"התחבר"}
        </button>
      )}
    </div>
  );
};

// exp;
