import axios from "axios";
import { SiGithubactions } from "react-icons/si";
import Model from "../../components/Module";

import { useContext, useEffect, useState } from "react";

import Spinner from "~/components/Spinner";
import Actions from "~/components/admin/actions";
import { AdminDataContext } from "~/context/adminContext";
import Head from "next/head";
import { headerType, useAdminData } from "~/hooks/admin/helper";
import TableData from "~/components/admin/Table";

export async function getServerSideProps(context: any) {
  const { params } = context;
  if (params.password == "123") {
    const orders = await axios(
      "https://script.google.com/macros/s/AKfycbyfBt4Ueq6GAULew28xiJrl7T-dIfNDkNm1VZmAzLiD1MySjnTkP5icgtCARxNZ_wN4/exec?type=orders",
      { withCredentials: false }
    ).then((res) => res.data);
    // const config = await axios(
    //   "https://script.google.com/macros/s/AKfycbyfBt4Ueq6GAULew28xiJrl7T-dIfNDkNm1VZmAzLiD1MySjnTkP5icgtCARxNZ_wN4/exec?type=orders",
    //   { withCredentials: false }
    // ).then((res) => res.data);
    return {
      props: {
        data: {
          orders: orders,
        },
        // config: config?.status ? config?.data?.headersConfig : null,
        config: null,
      },
    };
  }
}

export const AdminData = ({ data }: { data: any }) => {
  const [produceModule, togleProduceModule] = useState(false);
  const { viewType, setViewType } = useContext(AdminDataContext);
  const [loading, setLoading] = useState(false);
  const { headers, ordersData, setOrdersData } = useAdminData(data, loading);

  // useEffect(() => {}, [adminData, headers]);

  const handleClick = (e: any, lineID: any, type: string, from?: string) => {
    if (from && from == "row")
      setOrdersData((prev) => {
        let prevStatus: any;
        const newArray = prev?.map((line) => {
          if (line.rowID == lineID) {
            prevStatus = line.status ?? null;
            return { ...line, status: type };
          }
          return line;
        });
        if (prevStatus)
          setStatusCounter((prev) => ({
            ...prev,
            [type]: prev[type as keyof typeof prev] + 1,
            [prevStatus]: prev[prevStatus as keyof typeof prev] - 1,
          }));
        return newArray;
      });
  };

  return (
    <div className={" flex flex-col items-center justify-center"}>
      <Head>
        <title>גת אביגדור UI</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {loading ? (
          <Spinner />
        ) : (
          setViewType && (
            <div>
              <div className="mb-8 flex flex-row-reverse justify-center gap-6">
                <Actions />
                <h1 className="flex text-sm font-extrabold tracking-tight text-white ">
                  Bizi
                  <span className="text-[hsl(280,100%,70%)]">row</span>{" "}
                  <span>
                    {" "}
                    <SiGithubactions />
                  </span>
                </h1>

                <div className="flex gap-1">
                  <button
                    onClick={() => setViewType("במטריצה")}
                    className="text-bold w-20 bg-green-400 text-black"
                  >
                    במטריצה
                  </button>
                  <button
                    onClick={() => setViewType("למחוק")}
                    className="w-20 bg-red-400"
                  >
                    {" "}
                    למחוק
                  </button>
                  <button
                    onClick={() => setViewType("לא מויינו")}
                    className="text-bold w-20 bg-blue-300 text-black"
                  >
                    {" "}
                    לא מויינו
                  </button>
                  <button
                    onClick={() => setViewType("הכל")}
                    className="text-bold w-20 bg-gray-200 text-black"
                  >
                    {" "}
                    הכל
                  </button>
                </div>
                <button
                  onClick={() => {
                    togleProduceModule(true);
                  }}
                  className="flex w-20 justify-center bg-pink-300 text-center text-black hover:bg-red-500 hover:text-white"
                >
                  הפק
                </button>
              </div>
              {headers && (
                <div className="mb-4 flex w-full  flex-row-reverse justify-center">
                  {headers.map((cell: headerType, index: number) => {
                    if (cell.toShow)
                      return (
                        <p className="w-1/6 text-center text-[8px]">
                          {cell.replacmentName ?? cell.initialName}
                        </p>
                      );
                  })}
                  <button className="w-1/6 bg-green-400 text-[8px] font-bold text-black">
                    למטריצה
                  </button>
                  <button className="w-1/6 bg-red-400 text-[8px]">למחוק</button>
                </div>
              )}
              {headers && (
                <TableData
                  data={ordersData}
                  handleClick={handleClick}
                  type={viewType}
                />
              )}

              {produceModule && (
                <Model
                  toggleModule={togleProduceModule}
                  data={ordersData}
                  setLoading={setLoading}
                />
              )}
            </div>
          )
        )}
      </main>
    </div>
  );
};

export default AdminData;
